MyBlog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from .views import *

#always put app_name
app_name='Blog'
urlpatterns = [
    url(r'^$',post_list,name="lists"),
    url(r'^create',post_create,name='create'),
    #url(r'^details/(?P<id>\d+)/update',post_update,name="update"),
    url(r'^details/(?P<slug>[\w-]+)/update',post_update,name="update"),
    url(r'^details/(?P<slug>[\w-]+)/delete',post_delete,name='delete'),
    #passing id parameter in detail   detail/id
    #need to add app_name in urls in Blog --for namespace
    url(r'^details/(?P<slug>[\w-]+)',post_detail,name="details"),
]
# defining path for static files to be stored

MyBlog/MyBlog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from Accounts.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/',login_view,name="loginv"),
    path('logout/',logout_view,name="logoutv"),
    path('register/',register_view,name="registerv"),
    path('accounts/', include('django.contrib.auth.urls')),
    path('comments/',include("comments.urls",namespace='comments')),
    path('',include("Blog.urls",namespace='posts')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyBlog/Blog/models.py
from comments.models import Comment,CommentManager
from .counts import get_read_time
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.db.models.signals import pre_save
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify
#from markdown_deux import markdown
# not using markdown_deux since its not considering linebreaks instead using python markdown library
#for that install markdown lib using pip
from django.utils.safestring import mark_safe
import markdown
# Create your models here.
def upload_location(intsance,filename):
    return "{0}/{1}".format(intsance.id,filename)
# to check whether the slug has been created or not
def create_slug(instance,new_slug=None):
    slug=slugify(instance.title)
    if new_slug is not None:
        slug=new_slug
    qs_slug=Post.objects.filter(slug=slug).order_by('-id')
    exists=qs_slug.exists()
    if exists:
        #print(qs_slug.first().id)
        new_slug="%s-%s" %(slug,qs_slug.first().id)
        #print(new_slug)
        return create_slug(instance,new_slug)
    return slug

def pre_save_receiver(sender,instance,*args,**kwargs):
    if not instance.slug:
        instance.slug=create_slug(instance)

    if instance.content:
        htmlstring=instance.get_markdown()
        time=get_read_time(htmlstring)
        instance.read_time=time
        
class PostManager(models.Manager):
    def active(self,*args,**kwargs):
        return super(PostManager,self).filter(draft=False).filter(publish__lte=timezone.now())
class Post(models.Model):
    user=models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,default=1)
    title=models.CharField(max_length=100,blank=True,null=True)
    slug=models.SlugField(unique=True)
    image=models.ImageField(upload_to=upload_location,height_field='height_field',width_field='width_field',null=True,blank=True)
    height_field=models.IntegerField(default=50)
    width_field=models.IntegerField(default=50)
    content=models.TextField()
    draft=models.BooleanField(default=False)
    publish=models.DateField(auto_now=False,auto_now_add=False)
    read_time=models.TimeField(blank=True,null=True)
    timestamp=models.DateTimeField(auto_now=False,auto_now_add=True)
    updated=models.DateTimeField(auto_now=True,auto_now_add=False)
    objects=PostManager()
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        #return "/posts/details/%s" %(self.id)
        #never forget to add current_app, won't work without it
        return reverse("posts:details",kwargs={"slug":self.slug},current_app='Blog')

    def get_markdown(self):
        content=self.content
        #gives marked content
        mcontent=markdown.markdown(content, extensions=['markdown.extensions.nl2br'])
        return mark_safe(mcontent)

    @property
    def comments(self):
        return Comment.objects.filter_by_instance(self)

    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)
pre_save.connect(pre_save_receiver,sender=Post)

MyBlog/Blog/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *
from pagedown.widgets import PagedownWidget
class PostForm(forms.ModelForm):
    publish=forms.DateField(widget=forms.SelectDateWidget)
    content=forms.CharField(widget=PagedownWidget(show_preview=False))


    class Meta:
        model=Post
        fields=['title','content','image','draft','publish',]
    def clean_title(self):
        title=self.cleaned_data.get('title')
        if not title:
            raise forms.ValidationError("Title cannot be blank")
        return title

MyBlog/Blog/views.py
from .models import Post
from .forms import PostForm
from .counts import get_read_time
from comments.forms import CommentForm
from comments.models import Comment
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
# Create your views here.
from django.db.models import Q
from django import forms
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.shortcuts import render,get_object_or_404,redirect
from urllib.parse import quote_plus


def post_list(request):
    ptitle="Latest Posts"
    queryset_list=Post.objects.active()
    if request.user.is_superuser:
        queryset_list=Post.objects.all()
    query=request.GET.get("q")
    if query:
        queryset_list=queryset_list.filter(Q(title__icontains=query) | Q(content__icontains=query))
    paginator = Paginator(queryset_list,5) # Show 25 contacts per page
    page_var='abc'
    page = request.GET.get(page_var)
    queryset = paginator.get_page(page)
# to obtain 5 Latest posts
    context={
        'title':ptitle,
        'objlist':queryset,
        'page_var':page_var
        }
    return render(request,'base.html',context)
def post_create(request):
    if not (request.user.is_authenticated or request.user.is_superuser):
        raise Http404
    fname="Create Post"
    if request.method=='POST':
        form=PostForm(request.POST,request.FILES)
        if form.is_valid():
            instance=form.save(commit=False)
            instance.user=request.user
            print(request.user,instance.user)
            instance.save()
            #messages.success(request,"Successfully Created")
            return HttpResponseRedirect(instance.get_absolute_url())
    else:
        form=PostForm()

#messages.error(request,"Error in creating")
    context={'form':form,'fname':fname}
    return render(request,'createposts.html',context)

def post_update(request,slug):
    if not (request.user.is_superuser or request.user.is_authenticated):
        raise Http404
    fname="Update Post"
    queryset=get_object_or_404(Post,slug=slug)
    if not request.user.is_superuser:
        if queryset.user!=request.user:
            raise Http404
    if request.method=='POST':
        form=PostForm(request.POST,request.FILES,instance=queryset)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(queryset.get_absolute_url())
    else:
        form=PostForm(instance=queryset)
    context={'instance':queryset,'form':form,'fname':fname,}
    return render(request,'createposts.html',context)

def post_detail(request,slug):
    if not (request.user.is_authenticated or request.user.is_superuser):
        raise Http404
    queryset=get_object_or_404(Post,slug=slug)
    share_content=quote_plus(queryset.content)
    share_title=quote_plus(queryset.title)
    initial_data={
    'content_type':queryset.get_content_type,
    'object_id':queryset.id,
    }
    comment_form=CommentForm(request.POST or None,initial=initial_data)
    print(comment_form.is_valid())
    if comment_form.is_valid():
        c_type=comment_form.cleaned_data.get("content_type")
        content_type=ContentType.objects.get(model=c_type)
        obj_id=comment_form.cleaned_data.get("object_id")
        comment_text=comment_form.cleaned_data.get("comment_text")
        try:
            parent_id=request.POST.get("parent_id")
            parent_obj=Comment.objects.get(id=parent_id)
        except:
            parent_obj=None


        new_comment=Comment.objects.create(user=request.user,content_type=content_type,object_id=obj_id,
                                        comment_text=comment_text,parent=parent_obj)
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    #content_type=ContentType.objects.get_for_model(Post)
    #object_id=queryset.id
    #comments=Comment.objects.filter_by_instance(queryset)
    comments=queryset.comments
    context={'obj':queryset,'sharecontent':share_content,'sharetitle':share_title,'comments':comments,'comment_form':comment_form}
    return render(request,'detail.html',context)

def post_delete(request,slug):
    if not (request.user.is_authenticated or request.user.is_superuser):
        raise Http404
    queryset=get_object_or_404(Post,slug=slug)
    if queryset.user!=request.user:
        raise Http404
    queryset.delete()
    return redirect('posts:lists')

MyBlog/Blog/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>{% block head_title %}Latest Posts {%endblock head_title %}</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.1/css/all.css" integrity="sha384-O8whS3fhG2OnA5Kas0Y9l3cfpmYjapjI0E4theH4iuMD+pLhbf6JI0jIMfYcK3yZ" crossorigin="anonymous">
    {% block head_extra %}{% endblock head_extra%}
    <link href="{% static 'base.css' %}" rel="stylesheet" >
  </head>
  <body>
    <div class='container'>
      <header>
        <nav class='navbar navbar-expand-sm bg-light ml-auto'>
          <ol class= 'navbar-nav'>
              <li class='nav-item'><a class='nav-link' href='{% url "posts:lists" %}'>Home</a></li>
              <li class='nav-item'><a class='nav-link'href='{% url "posts:lists" %}'>Posts</a></li>
          </ol>
            <ol class='collapse navbar-collapse justify-content-end navbar-nav'>
              {% if not request.user.is_authenticated %}
              <li class='nav-item'><a class='nav-link' href="{% url 'loginv' %}">Login</a></li>
              <li class='nav-item'><a class='nav-link' href="{% url 'registerv' %}">Register</a></li>
            {% else %}
              <li class='nav-item'><a class='justify-content-end nav-link' href="{% url 'logoutv' %}">Logout</a></li>
            {% endif %}
          </ol>
        </nav>
      Welcome:{{request.user}}</header>
      {% block content %}
        <form method="GET" action="">
          <div class="input-group mb-3 col-sm-6">
            <input type="text"  class='form-control' name='q' placeholder="Search Posts">
            <div class="input-group-append">
              <!--<input type="submit" value="Search" class="btn btn-outline-secondary">-->
              <button type="submit" class="btn btn-outline-secondary"><i class="fas fa-search"></i></button>
            </div>
          </div>
        </form>
       <h1>Latest Posts</h1>
     <div class='col-sm-8 col-sm-offest-2'>
             {% for i in objlist %}
              <div class="row">
               <div class='col-sm-12'>
                 <div class="thumbnail border rounded border-primary">
                     <div class='caption col-sm-10 col-sm-offset-2'>
                       <h3><a href="{{i.get_absolute_url}}">{{i.title}}</a></h3>
                       <p><small>created by {{i.user}} on : {{i.publish}}</small><br>
                         {% if i.draft %}<small><span> Draft</span></small>{% endif %}
                         <div class='post-content'>
                         <p>{{i.get_markdown|truncatechars_html:10}}</p>
                       </div>
                         {% if i.image %}
                          <img src="{{i.image.url}}"class='img-fluid' alt="img field">
                          <br>
                        {% endif %}
                        <p><a href="{{i.get_absolute_url}}"class="btn btn-primary" role="button">View</a></p>
                      </div>
                 </div>
                </div>
                <br>
              </div>
              <br>
            {% endfor %}
            <a href="{% url "posts:create" %}" class="btn btn-primary" role="button">New Post</a></p>
       </div>
     </div>
       <footer>
      <div class="pagination">
    <span class="step-links">
        {% if objlist.has_previous %}
            <a href="?{{page_var}}=1"> first</a>
            <a href="?{{page_var}}={{ objlist.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ objlist.number }} of {{ objlist.paginator.num_pages }}.
        </span>

        {% if objlist.has_next %}
            <a href="?{{page_var}}={{ objlist.next_page_number }}">next</a>
            <a href="?{{page_var}}={{ obljlist.paginator.num_pages }}">lasts</a>
        {% endif %}
    </span>
</div>
</footer>
  {% endblock content %}
</div>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
  <script
  src="https://code.jquery.com/jquery-1.12.4.min.js"
  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js" integrity="sha384-u/bQvRA/1bobcXlcEYpsEdFVK/vJs3+T+nXLsBYJthmdBuavHvAW6UsmqO2Gd/F9" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.4.0/marked.min.js"></script>

  <script src="{% static 'basescripts.js' %}">

  </script>

  </body>

</html>

MyBlog/Blog/templates/createposts.html
{% extends "base.html" %}
{% block head_title %}Create New Post{%endblock head_title %}
{% block head_extra %}
  {{form.media}}
{% endblock head_extra %}
{% block content %}
<div class='container'>
  <div class='row'>
    <div class='col-sm-6'>
      <h1>Preview</h1>
      <h3 id='preview-title'></h3>
      <p id='preview-content'></p>
    </div>
    <div class='col-sm-4'>
      <h2>{{fname}}</h2>
      <br>
      {% if instance %}
        <form method="POST" action='{% url "posts:update" slug=instance.slug %}' enctype="multipart/form-data">
      {% else %}
        <form method="POST" action='' enctype="multipart/form-data">
      {% endif %}
      {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="{{fname}}" class='btn btn-primary'>
      </form>
    </div>

  </div>
  </div>

</div>
{% endblock content %}

MyBlog/Blog/templates/detail.html
{% extends "base.html" %}
{% block content %}
<div class='container'>
  <div class='col-sm-6 col-sm-offset-3'>
    {% if obj.image %}
      <img src="{{obj.image.url}}" alt="img field" class='img-fluid'>
    {% endif %}
    <h1>{{obj.title}}</h1>{% if obj.draft %}<small><span> Draft</span></small>{% endif %}
    <small>created by {{obj.user}} on: {{obj.publish}}</small>
    <br><small>Read time:{{obj.read_time|time:'i'}} minutes</small>
    <br>
    <div class="fb-like" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="false" data-share="true"></div>
    <br>
    <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}" role="button">
      Facebook
    </a>
    <a href="https://twitter.com/home?status={{sharecontent}}{{request.build_absolute_uri}}/">
      Twitter
    </a>
    <a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}/&title={{sharetitle}}&summary={{sharecontent}}!&source={{request.build_absolute_uri}}">
      Linkedin
    </a>
    <a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'>Google+</a>
    <br>
    <hr>
    <div class='row'>
      <div class='col-sm-offset-2'>
        <div class='post-content'>
          {{obj.id}}
          <br>
        <p>{{obj.get_markdown}}</p>
      </div>
        <hr>
        <div class=lead>Comments</div>
        <hr>
        <form method="POST" action=" ">
          {% csrf_token %}
          {{comment_form}}
          <input type="submit" value="Post Comment" class="btn btn-default">
        </form>

        {% for comment in comments %}
          <br>
          <blockquote class="blockquote">
            <p class="mb-0">{{comment.comment_text}}</p>
            <footer class="blockquote-footer">by <cite title="Source Title"> {{comment.user.username}} on {{comment.timestamp|timesince}} ago|
              {% if comment.children.count > 0 %}
                {% if comment.children.count > 1 %}
                  {{comment.children.count}} Comments|
                  {% endif %}
                  {{comment.children.count}} Comment|
                  {% endif %}</cite><a href=# class='reply-btn'>reply|</a><a href={{comment.get_absolute_url}}>Thread</a></footer>
            <div class='comment-reply'>
              {% for child in comment.children %}
              <blockquote class="blockquote">
                <p class="mb-0">{{child.comment_text}}</p>
                <footer class="blockquote-footer">by <cite title="Source Title"> {{child.user.username}} on {{child.timestamp|timesince}} ago|
                  <a href=#>reply</a></cite>|
                </footer>
              </blockquote>
              {% endfor %}
              <form method="POST" action=" ">
                {% csrf_token %}
                <input type="hidden" name="parent_id" value='{{comment.id}}'>
                {{comment_form}}
                <input type="submit" value="Reply" class="btn btn-default">
              </form>
          </div>

          </blockquote>
          <!--{{comment.content_object}}-->
          <hr>
        {% endfor %}


        <!--<div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div>

    --></div>
    </div>
  </div>
  <br>

  <p><a href="{% url "posts:delete" slug=obj.slug %}"class="btn btn-primary" role="button">Delete</a>
  <a href="{% url "posts:update" slug=obj.slug %}"class="btn btn-primary" role="button">Update</a></p>
  <p><a href="{% url "posts:create" %}" class="btn btn-primary" role="button">Create New Post</a></p>

<!--<form method="POST" action="{% url "posts:create" %}">
  {% csrf_token %}
  <input type="submit" value="Create New">
</form>-->
{% endblock content %}